let pendingExcelImport=null;
const DEFAULT_EXCEL_TEXT_FIELDS=[
  {key:"headline",label:"主标题",layer:"文字_主标题_黑",aliases:["文字_主标题_黑","主标题黑","主标题"]},
  {key:"accent",label:"强调标题",layer:"文字_强调标题_红",aliases:["文字_强调标题_红","强调标题红","强调标题"]},
  {key:"campaign",label:"活动文案",layer:"文字_活动文案",aliases:["文字_活动文案","活动文案"]},
  {key:"productName",label:"产品名称",layer:"文字_产品名称",aliases:["文字_产品名称","产品名称"]},
  {key:"purchaseDetail",label:"底部购买明细",layer:"文字_底部购买明细",aliases:["文字_底部购买明细","底部购买明细","购买明细"]},
  {key:"giftDetail",label:"底部赠品明细",layer:"文字_底部赠品明细",aliases:["文字_底部赠品明细","底部赠品明细","赠品明细"]}
];
const EXCEL_TEXT_FIELDS=DEFAULT_EXCEL_TEXT_FIELDS.map(field=>({...field,aliases:[...field.aliases]}));
function excelKey(value){return String(value||"").replace(/[\s*＊()（）]/g,"").toLowerCase()}
function excelValue(row,aliases){const wanted=aliases.map(excelKey);for(const key of Object.keys(row))if(wanted.includes(excelKey(key)))return String(row[key]??"").trim();return""}
function excelHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function excelTokens(value){return String(value||"").split(/[,，;；\n]+/).map(s=>s.trim()).filter(Boolean).flatMap(token=>{const match=token.match(/^(.+?)(?:\s*[*×xX]\s*(\d+))?$/),code=(match?match[1]:token).trim(),qty=Math.max(1,Math.min(20,Number(match?.[2])||1));return Array.from({length:qty},()=>code)})}
function assetStem(name){return String(name||"").replace(/\.[^.]+$/,"").toLowerCase()}
function excelSheetRows(sheet,requiredHeader){const matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:"",raw:false}),index=matrix.findIndex(row=>row.some(cell=>excelKey(cell)===excelKey(requiredHeader)));if(index<0)return[];return XLSX.utils.sheet_to_json(sheet,{defval:"",raw:false,range:index})}
function findImportedAsset(type,code,catalog){const entry=catalog.get(excelKey(code)),fileName=entry?.fileName||"",list=state.assets[type]||[],exact=fileName&&list.find(a=>a.file.name.toLowerCase()===fileName.toLowerCase());if(exact)return exact;const c=String(code).trim().toLowerCase();return list.find(a=>{const stem=assetStem(a.file.name);return stem===c||stem.startsWith(c+"_")||stem.startsWith(c+"-")})||null}
function buildExcelOrder(mainRefs,giftRefs,priority){const pool=new Map;for(const ref of mainRefs.concat(giftRefs)){if(!pool.has(excelKey(ref.code)))pool.set(excelKey(ref.code),[]);pool.get(excelKey(ref.code)).push(`${ref.type}:${ref.id}:${ref.instance}`)}const result=[];for(const code of excelTokens(priority)){const arr=pool.get(excelKey(code));if(arr?.length)result.push(arr.shift())}for(const arr of pool.values())result.push(...arr);return result}
async function handleExcelImport(file){if(!file)return;const input=$("excelInput");try{if(!globalThis.XLSX)throw new Error("Excel 读取组件未加载，请刷新网站后重试");const workbook=XLSX.read(await file.arrayBuffer(),{type:"array"}),taskSheet=workbook.Sheets["搭配任务"]||workbook.Sheets[workbook.SheetNames[0]];if(!taskSheet)throw new Error("Excel 中没有可读取的工作表");const taskRows=excelSheetRows(taskSheet,"搭配编号"),assetSheet=workbook.Sheets["素材说明"],assetRows=assetSheet?excelSheetRows(assetSheet,"素材编号"):[],catalog=new Map;for(const row of assetRows){const code=excelValue(row,["素材编号"]),fileName=excelValue(row,["文件名"]),type=excelValue(row,["素材类型"]);if(code)catalog.set(excelKey(code),{code,fileName,type})}const rows=[];for(let index=0;index<taskRows.length;index++){const row=taskRows[index],number=excelValue(row,["搭配编号"]);if(!number)continue;const name=excelValue(row,["搭配名称"])||`搭配 ${number}`,mainCodes=excelTokens(excelValue(row,["主品编号"])),giftCodes=excelTokens(excelValue(row,["赠品编号"])),issues=[],warnings=[],main=[],gift=[],mainRefs=[],giftRefs=[],mainSeen={},giftSeen={};if(!mainCodes.length)issues.push("没有填写主品编号");for(const code of mainCodes){const asset=findImportedAsset("main",code,catalog);if(!asset){issues.push(`缺少主品 ${code}`);continue}main.push(asset.id);const instance=mainSeen[asset.id]=(mainSeen[asset.id]||0)+1;mainRefs.push({type:"main",id:asset.id,instance,code})}for(const code of giftCodes){const asset=findImportedAsset("gift",code,catalog);if(!asset){issues.push(`缺少赠品 ${code}`);continue}gift.push(asset.id);const instance=giftSeen[asset.id]=(giftSeen[asset.id]||0)+1;giftRefs.push({type:"gift",id:asset.id,instance,code})}const text={};for(const field of EXCEL_TEXT_FIELDS){const value=excelValue(row,field.aliases);text[field.key]=value;if((field.key==="headline"||field.key==="campaign"||field.key==="productName")&&!value)issues.push(`缺少${field.label}`);const limit=field.key.includes("Detail")?90:field.key==="accent"?18:30;if([...value].length>limit)warnings.push(`${field.label}较长`)}const priority=excelValue(row,["排版优先级"]),combo={id:crypto.randomUUID(),name,excelNumber:number,main,gift,order:buildExcelOrder(mainRefs,giftRefs,priority),previewLayout:null,sun:defaultSun(),textContent:text};rows.push({number,name,combo,issues:[...new Set(issues)],warnings:[...new Set(warnings)],mainCodes,giftCodes})}if(!rows.length)throw new Error("没有找到有效搭配。请使用“搭配任务”工作表并填写搭配编号");const errorCount=rows.reduce((n,r)=>n+r.issues.length,0),warningCount=rows.reduce((n,r)=>n+r.warnings.length,0);pendingExcelImport={fileName:file.name,rows,errorCount,warningCount};renderExcelImportPreview()}catch(error){toast("Excel 导入失败："+error.message)}finally{input.value=""}}
function renderExcelImportPreview(){const data=pendingExcelImport,dialog=$("excelDialog");if(!data)return;$("excelSummary").textContent=`${data.fileName} · ${data.rows.length} 个搭配 · ${data.errorCount} 个错误 · ${data.warningCount} 个提醒`;const allIssues=data.rows.flatMap(r=>r.issues.map(x=>`${r.number}：${x}`));$("excelIssues").innerHTML=allIssues.length?`<strong>请先解决以下问题：</strong><br>${allIssues.map(excelHtml).join("<br>")}`:"<strong>匹配检查通过，可以导入。</strong>";$("excelIssues").className="excel-issues "+(allIssues.length?"bad":"ok");$("excelRows").innerHTML=data.rows.map(r=>`<tr><td><b>${excelHtml(r.number)}</b><br>${excelHtml(r.name)}</td><td>${EXCEL_TEXT_FIELDS.filter(f=>r.combo.textContent[f.key]).length}/${EXCEL_TEXT_FIELDS.length} 项</td><td>${r.mainCodes.map(excelHtml).join("、")||"—"}</td><td>${r.giftCodes.map(excelHtml).join("、")||"—"}</td><td class="${r.issues.length?"bad":r.warnings.length?"warn":"ok"}">${r.issues.length?excelHtml(r.issues.join("；")):r.warnings.length?excelHtml(r.warnings.join("；")):"可导入"}</td></tr>`).join("");$("excelAppend").disabled=$("excelReplace").disabled=data.errorCount>0;dialog.showModal()}
function applyExcelImport(mode){const data=pendingExcelImport;if(!data||data.errorCount)return;pushGlobalHistory();const combos=data.rows.map(r=>r.combo);if(mode==="replace")state.combos=combos;else state.combos.push(...combos);state.activeComboId=combos[0]?.id||state.activeComboId;$("excelDialog").close();pendingExcelImport=null;renderCombos();toast(`已导入 ${combos.length} 个搭配`)}

// 策划表转换器：只调整字段去向，永远不改写策划填写的原始单元格内容。
let pendingPlannerConversion=null;
const PLANNER_DEFAULT_SOURCES={headline:"功效文案",accent:"直播价",campaign:"利益点",productName:"主品名称",purchaseDetail:"主品名称",giftDetail:"赠品机制"};
function plannerTargets(){return EXCEL_TEXT_FIELDS.map(field=>({key:field.key,label:field.label,layer:field.layer,defaultSource:PLANNER_DEFAULT_SOURCES[field.key]||field.label}))}
function plannerCell(value){return value==null?"":String(value)}
function plannerNormalized(value){return plannerCell(value).toLowerCase().replace(/\.[^.]+$/g,"").replace(/[（(][^）)]*[）)]/g,"").replace(/欧莱雅|l['’]?oreal|官方|正装|产品|新旧包装混发/g,"").replace(/[\s\-_—·，,。.;；:：、【】\[\]（）()]/g,"").replace(/\d+(?:\.\d+)?(?:ml|g|克|毫升|支|个|件|片|盒|包)?/gi,"")}
function plannerAssetCode(asset){return assetStem(asset?.file?.name||asset?.name||"")}
function plannerMatchAsset(type,name){const query=plannerNormalized(name);if(!query||query==="/")return null;let best=null,bestScore=0;for(const asset of state.assets[type]||[]){const candidate=plannerNormalized(asset.file?.name||asset.name);if(!candidate)continue;let score=0;if(candidate===query)score=100;else if(candidate.includes(query)||query.includes(candidate))score=80-Math.abs(candidate.length-query.length);else{const chars=[...new Set(query)],shared=chars.filter(c=>candidate.includes(c)).length;score=Math.round(shared/Math.max(chars.length,1)*55)}if(score>bestScore){bestScore=score;best=asset}}return bestScore>=35?{asset:best,score:bestScore,kind:bestScore>=75?"exact":"suggested"}:null}
function plannerGiftParts(value){const raw=plannerCell(value);if(!raw.trim()||raw.trim()==="/")return[];return raw.split(/[+＋\n]+/).map(part=>part.trim()).filter(Boolean).map(part=>{const m=part.match(/(?:[*×xX]\s*(\d+))\s*(?:[（(].*)?$/),qty=Math.max(1,Math.min(20,Number(m?.[1])||1)),name=part.replace(/(?:[*×xX]\s*\d+)\s*(?:[（(].*)?$/g,"").replace(/[（(].*?[）)]/g,"").trim();return{raw:part,name,qty}})}
function plannerHeaderIndex(headers,name){const wanted=excelKey(name);return headers.findIndex(h=>excelKey(h)===wanted)}
function plannerValue(record,source){const i=record.headerMap.get(excelKey(source));return i==null?"":plannerCell(record.values[i])}
function plannerBuildRows(){const data=pendingPlannerConversion;if(!data)return;const targets=plannerTargets();data.rows=data.records.map((record,index)=>{const text={};for(const target of targets)text[target.key]=plannerValue(record,data.mapping[target.key]);const mainOriginal=plannerValue(record,"主品名称"),giftOriginal=plannerValue(record,"赠品机制"),mainMatch=plannerMatchAsset("main",mainOriginal),giftParts=plannerGiftParts(giftOriginal),giftMatches=[],giftCodes=[];for(const part of giftParts){const match=plannerMatchAsset("gift",part.name);giftMatches.push({...part,match});const code=match?plannerAssetCode(match.asset):part.name;for(let q=0;q<part.qty;q++)giftCodes.push(code)}const mainCode=mainMatch?plannerAssetCode(mainMatch.asset):mainOriginal.trim(),warnings=[];if(!mainMatch&&mainOriginal.trim()&&mainOriginal.trim()!=="/")warnings.push("主品待匹配");for(const gift of giftMatches)if(!gift.match)warnings.push(`赠品待匹配：${gift.name}`);const number=String(index+1).padStart(3,"0"),taskTitle=record.context.tb标题||`策划表第 ${record.sourceRow} 行`,name=`${taskTitle}${mainOriginal?`｜${mainOriginal}`:""}`;return{number,name,sourceRow:record.sourceRow,record,text,mainOriginal,giftOriginal,mainCode,giftCodes,mainMatch,giftMatches,warnings}});renderPlannerConversionPreview()}
async function handlePlannerWorkbook(file){const input=$("plannerExcelInput");if(!file)return;try{if(!globalThis.XLSX)throw new Error("Excel 读取组件未加载，请刷新网站后重试");const workbook=XLSX.read(await file.arrayBuffer(),{type:"array",cellText:true}),sheetName=workbook.SheetNames.find(name=>/下单/.test(name))||workbook.SheetNames[0],sheet=workbook.Sheets[sheetName];if(!sheet)throw new Error("表格中没有可读取的工作表");const matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:"",raw:false,blankrows:false}),headerRow=matrix.findIndex(row=>row.some(v=>excelKey(v)===excelKey("主品名称"))&&row.some(v=>excelKey(v)===excelKey("赠品机制")));if(headerRow<0)throw new Error("没有找到“主品名称”和“赠品机制”表头");const headers=matrix[headerRow].map(plannerCell),headerMap=new Map(headers.map((h,i)=>[excelKey(h),i])),required=["主品名称","赠品机制","利益点","功效文案"].filter(h=>!headerMap.has(excelKey(h)));if(required.length)throw new Error(`缺少策划字段：${required.join("、")}`);const metaNames=["mo'pi","收稿时间","下单人","tb标题","店铺/达人模板"],context=Object.fromEntries(metaNames.map(k=>[k,""])),records=[];for(let r=headerRow+1;r<matrix.length;r++){const values=headers.map((_,i)=>plannerCell(matrix[r]?.[i]));for(const name of metaNames){const i=headerMap.get(excelKey(name));if(i!=null&&values[i]!=="")context[name]=values[i]}const hasContent=["主品名称","直播价","赠品机制","利益点","功效文案","icon","注释","赠品标题赠品标识记得图上标识要大点哦！","备注"].some(name=>{const i=headerMap.get(excelKey(name));return i!=null&&values[i]!==""});if(!hasContent)continue;records.push({sourceRow:r+1,values,headerMap,context:{...context}})}if(!records.length)throw new Error("没有识别到策划产品行");const mapping={};for(const target of plannerTargets())mapping[target.key]=headers.find(h=>excelKey(h)===excelKey(target.defaultSource))||"";pendingPlannerConversion={fileName:file.name,sheetName,headers,headerRow:headerRow+1,sourceMatrix:matrix.map(row=>headers.map((_,i)=>plannerCell(row?.[i]))),records,mapping,rows:[]};plannerBuildRows();$("plannerDialog").showModal()}catch(error){toast("策划表转换失败："+error.message)}finally{input.value=""}}
function renderPlannerMappings(){const data=pendingPlannerConversion;if(!data)return;const options=[`<option value="">不填写</option>`].concat(data.headers.filter(Boolean).map(h=>`<option value="${excelHtml(h)}">${excelHtml(h)}</option>`)).join("");$("plannerMappings").innerHTML=plannerTargets().map(target=>`<label><span>${excelHtml(target.layer)} <small>（${excelHtml(target.label)}）</small></span><select data-planner-target="${target.key}">${options}</select></label>`).join("");document.querySelectorAll("[data-planner-target]").forEach(select=>{select.value=data.mapping[select.dataset.plannerTarget]||"";select.onchange=()=>{data.mapping[select.dataset.plannerTarget]=select.value;plannerBuildRows()}})}
function renderPlannerConversionPreview(){const data=pendingPlannerConversion;if(!data)return;if(!$("plannerMappings").children.length)renderPlannerMappings();const targets=plannerTargets(),unresolved=data.rows.reduce((n,r)=>n+r.warnings.length,0),exactMain=data.rows.filter(r=>r.mainMatch?.kind==="exact").length,matchedGifts=data.rows.reduce((n,r)=>n+r.giftMatches.filter(g=>g.match).length,0),giftTotal=data.rows.reduce((n,r)=>n+r.giftMatches.length,0);$("plannerSummary").textContent=`${data.fileName} · ${data.sheetName} · 识别 ${data.rows.length} 条方案`;$('plannerIssues').textContent=`文字表头将使用 ${targets.length} 个 PSD 可变文字图层名；主品高置信匹配 ${exactMain}/${data.rows.length}；赠品匹配 ${matchedGifts}/${giftTotal}；${unresolved?`还有 ${unresolved} 项素材编号需要检查。`:`素材名称检查通过。`}`;$("plannerRows").innerHTML=data.rows.map(row=>{const textLines=targets.map(t=>row.text[t.key]?`${t.layer} ← ${data.mapping[t.key]}\n${row.text[t.key]}`:"").filter(Boolean).join("\n\n"),mainLabel=row.mainCode||"—",giftLabel=row.giftCodes.join("、")||"—",status=row.warnings.length?row.warnings.join("；"):(row.mainMatch?.kind==="suggested"?"主品为相似匹配，请检查":"可导出");return`<tr><td><b>${row.number}</b><br>${excelHtml(row.name)}<br><small>源表第 ${row.sourceRow} 行</small></td><td class="planner-original">${excelHtml(row.mainOriginal)||"—"}</td><td class="planner-original">${excelHtml(row.giftOriginal)||"—"}</td><td>${excelHtml(textLines)||"—"}</td><td><b>主品：</b>${excelHtml(mainLabel)}<br><b>赠品：</b>${excelHtml(giftLabel)}</td><td class="${row.warnings.length?'planner-status-bad':row.mainMatch?.kind==='suggested'?'planner-status-warn':'planner-status-ok'}">${excelHtml(status)}</td></tr>`}).join("")}
function plannerPriority(row){const refs=[];if(row.mainCode)refs.push(row.mainCode);refs.push(...row.giftCodes);return refs.join(",")}
function plannerStandardData(){const data=pendingPlannerConversion,targets=plannerTargets();return data.rows.map(row=>{const result={"搭配编号":row.number,"搭配名称":row.name};for(const target of targets)result[target.layer]=row.text[target.key]??"";Object.assign(result,{"主品编号":row.mainCode,"赠品编号":row.giftCodes.join(","),"排版优先级":plannerPriority(row),"模板编号":"","源表行号":row.sourceRow,"转换状态":row.warnings.join("；")});return result})}
function plannerSetWidths(sheet,widths){sheet["!cols"]=widths.map(w=>({wch:w}))}
function exportPlannerStandardWorkbook(){const data=pendingPlannerConversion;if(!data)return;try{const book=XLSX.utils.book_new(),targets=plannerTargets(),rows=plannerStandardData(),headers=["搭配编号","搭配名称",...targets.map(t=>t.layer),"主品编号","赠品编号","排版优先级","模板编号","源表行号","转换状态"],task=XLSX.utils.json_to_sheet(rows,{header:headers});plannerSetWidths(task,headers.map((_,i)=>i===0?10:i===1?42:i<2+targets.length?32:i===2+targets.length?28:i===3+targets.length?46:24));task["!autofilter"]={ref:`A1:${XLSX.utils.encode_col(headers.length-1)}${rows.length+1}`};XLSX.utils.book_append_sheet(book,task,"搭配任务");const assets=[];for(const type of ["main","gift"])for(const asset of state.assets[type]||[])assets.push({"素材编号":plannerAssetCode(asset),"文件名":asset.file?.name||asset.name,"素材类型":type==="main"?"主品":"赠品","文件夹路径":asset.relativePath||""});const assetSheet=XLSX.utils.json_to_sheet(assets,{header:["素材编号","文件名","素材类型","文件夹路径"]});plannerSetWidths(assetSheet,[32,42,10,55]);XLSX.utils.book_append_sheet(book,assetSheet,"素材说明");const original=XLSX.utils.aoa_to_sheet(data.sourceMatrix);plannerSetWidths(original,data.headers.map((h,i)=>i<5?20:i===8||i===12?46:26));XLSX.utils.book_append_sheet(book,original,"策划原文_禁止修改");const mappingRows=targets.map(t=>[t.layer,data.mapping[t.key]||"不填写",t.label,"只复制原单元格内容，不润色、不删减、不纠错"]),note=XLSX.utils.aoa_to_sheet([["PSD文字图层名","策划来源字段","网站字段","保护规则"],...mappingRows,["系统字段","主品编号、赠品编号、排版优先级、模板编号","网站/脚本使用","与文字通道分离，不覆盖策划原文"],["说明","素材编号属于系统识别结果，可以检查和修改；“策划原文_禁止修改”保留本次读取的完整原文。","",""]]);plannerSetWidths(note,[34,68,22,52]);XLSX.utils.book_append_sheet(book,note,"字段映射");const base=data.fileName.replace(/\.[^.]+$/,"");XLSX.writeFile(book,`${base}_标准搭配表.xlsx`,{compression:true});toast(`已导出 ${rows.length} 条标准搭配：文字与产品编号已分开`)}catch(error){toast("导出标准表失败："+error.message)}}
