let pendingExcelImport=null;
const EXCEL_TEXT_FIELDS=[
  {key:"headline",label:"主标题",layer:"文字_主标题_黑",aliases:["主标题黑","主标题"]},
  {key:"accent",label:"强调标题",layer:"文字_强调标题_红",aliases:["强调标题红","强调标题"]},
  {key:"campaign",label:"活动文案",layer:"文字_活动文案",aliases:["活动文案"]},
  {key:"productName",label:"产品名称",layer:"文字_产品名称",aliases:["产品名称"]},
  {key:"purchaseDetail",label:"底部购买明细",layer:"文字_底部购买明细",aliases:["底部购买明细","购买明细"]},
  {key:"giftDetail",label:"底部赠品明细",layer:"文字_底部赠品明细",aliases:["底部赠品明细","赠品明细"]}
];
function excelKey(value){return String(value||"").replace(/[\s*＊()（）]/g,"").toLowerCase()}
function excelValue(row,aliases){const wanted=aliases.map(excelKey);for(const key of Object.keys(row))if(wanted.includes(excelKey(key)))return String(row[key]??"").trim();return""}
function excelHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function excelTokens(value){return String(value||"").split(/[,，;；\n]+/).map(s=>s.trim()).filter(Boolean).flatMap(token=>{const match=token.match(/^(.+?)(?:\s*[*×xX]\s*(\d+))?$/),code=(match?match[1]:token).trim(),qty=Math.max(1,Math.min(20,Number(match?.[2])||1));return Array.from({length:qty},()=>code)})}
function assetStem(name){return String(name||"").replace(/\.[^.]+$/,"").toLowerCase()}
function excelSheetRows(sheet,requiredHeader){const matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:"",raw:false}),index=matrix.findIndex(row=>row.some(cell=>excelKey(cell)===excelKey(requiredHeader)));if(index<0)return[];return XLSX.utils.sheet_to_json(sheet,{defval:"",raw:false,range:index})}
function findImportedAsset(type,code,catalog){const entry=catalog.get(excelKey(code)),fileName=entry?.fileName||"",list=state.assets[type]||[],exact=fileName&&list.find(a=>a.file.name.toLowerCase()===fileName.toLowerCase());if(exact)return exact;const c=String(code).trim().toLowerCase();return list.find(a=>{const stem=assetStem(a.file.name);return stem===c||stem.startsWith(c+"_")||stem.startsWith(c+"-")})||null}
function buildExcelOrder(mainRefs,giftRefs,priority){const pool=new Map;for(const ref of mainRefs.concat(giftRefs)){if(!pool.has(excelKey(ref.code)))pool.set(excelKey(ref.code),[]);pool.get(excelKey(ref.code)).push(`${ref.type}:${ref.id}:${ref.instance}`)}const result=[];for(const code of excelTokens(priority)){const arr=pool.get(excelKey(code));if(arr?.length)result.push(arr.shift())}for(const arr of pool.values())result.push(...arr);return result}
async function handleExcelImport(file){if(!file)return;const input=$("excelInput");try{if(!globalThis.XLSX)throw new Error("Excel 读取组件未加载，请刷新网站后重试");const workbook=XLSX.read(await file.arrayBuffer(),{type:"array"}),taskSheet=workbook.Sheets["搭配任务"]||workbook.Sheets[workbook.SheetNames[0]];if(!taskSheet)throw new Error("Excel 中没有可读取的工作表");const taskRows=excelSheetRows(taskSheet,"搭配编号"),assetSheet=workbook.Sheets["素材说明"],assetRows=assetSheet?excelSheetRows(assetSheet,"素材编号"):[],catalog=new Map;for(const row of assetRows){const code=excelValue(row,["素材编号"]),fileName=excelValue(row,["文件名"]),type=excelValue(row,["素材类型"]);if(code)catalog.set(excelKey(code),{code,fileName,type})}const rows=[];for(let index=0;index<taskRows.length;index++){const row=taskRows[index],number=excelValue(row,["搭配编号"]);if(!number)continue;const name=excelValue(row,["搭配名称"])||`搭配 ${number}`,mainCodes=excelTokens(excelValue(row,["主品编号"])),giftCodes=excelTokens(excelValue(row,["赠品编号"])),issues=[],warnings=[],main=[],gift=[],mainRefs=[],giftRefs=[],mainSeen={},giftSeen={};if(!mainCodes.length)issues.push("没有填写主品编号");for(const code of mainCodes){const asset=findImportedAsset("main",code,catalog);if(!asset){issues.push(`缺少主品 ${code}`);continue}main.push(asset.id);const instance=mainSeen[asset.id]=(mainSeen[asset.id]||0)+1;mainRefs.push({type:"main",id:asset.id,instance,code})}for(const code of giftCodes){const asset=findImportedAsset("gift",code,catalog);if(!asset){issues.push(`缺少赠品 ${code}`);continue}gift.push(asset.id);const instance=giftSeen[asset.id]=(giftSeen[asset.id]||0)+1;giftRefs.push({type:"gift",id:asset.id,instance,code})}const text={};for(const field of EXCEL_TEXT_FIELDS){const value=excelValue(row,field.aliases);text[field.key]=value;if((field.key==="headline"||field.key==="campaign"||field.key==="productName")&&!value)issues.push(`缺少${field.label}`);const limit=field.key.includes("Detail")?90:field.key==="accent"?18:30;if([...value].length>limit)warnings.push(`${field.label}较长`)}const priority=excelValue(row,["排版优先级"]),combo={id:crypto.randomUUID(),name,excelNumber:number,main,gift,order:buildExcelOrder(mainRefs,giftRefs,priority),previewLayout:null,sun:defaultSun(),textContent:text};rows.push({number,name,combo,issues:[...new Set(issues)],warnings:[...new Set(warnings)],mainCodes,giftCodes})}if(!rows.length)throw new Error("没有找到有效搭配。请使用“搭配任务”工作表并填写搭配编号");const errorCount=rows.reduce((n,r)=>n+r.issues.length,0),warningCount=rows.reduce((n,r)=>n+r.warnings.length,0);pendingExcelImport={fileName:file.name,rows,errorCount,warningCount};renderExcelImportPreview()}catch(error){toast("Excel 导入失败："+error.message)}finally{input.value=""}}
function renderExcelImportPreview(){const data=pendingExcelImport,dialog=$("excelDialog");if(!data)return;$("excelSummary").textContent=`${data.fileName} · ${data.rows.length} 个搭配 · ${data.errorCount} 个错误 · ${data.warningCount} 个提醒`;const allIssues=data.rows.flatMap(r=>r.issues.map(x=>`${r.number}：${x}`));$("excelIssues").innerHTML=allIssues.length?`<strong>请先解决以下问题：</strong><br>${allIssues.map(excelHtml).join("<br>")}`:"<strong>匹配检查通过，可以导入。</strong>";$("excelIssues").className="excel-issues "+(allIssues.length?"bad":"ok");$("excelRows").innerHTML=data.rows.map(r=>`<tr><td><b>${excelHtml(r.number)}</b><br>${excelHtml(r.name)}</td><td>${EXCEL_TEXT_FIELDS.filter(f=>r.combo.textContent[f.key]).length}/6 项</td><td>${r.mainCodes.map(excelHtml).join("、")||"—"}</td><td>${r.giftCodes.map(excelHtml).join("、")||"—"}</td><td class="${r.issues.length?"bad":r.warnings.length?"warn":"ok"}">${r.issues.length?excelHtml(r.issues.join("；")):r.warnings.length?excelHtml(r.warnings.join("；")):"可导入"}</td></tr>`).join("");$("excelAppend").disabled=$("excelReplace").disabled=data.errorCount>0;dialog.showModal()}
function applyExcelImport(mode){const data=pendingExcelImport;if(!data||data.errorCount)return;const combos=data.rows.map(r=>r.combo);if(mode==="replace")state.combos=combos;else state.combos.push(...combos);state.activeComboId=combos[0]?.id||state.activeComboId;$("excelDialog").close();pendingExcelImport=null;renderCombos();toast(`已导入 ${combos.length} 个搭配`)}
